format = """
$directory\
$git_branch\
$git_status\
$python\
$line_break\
$character"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
crust = "#11111b"
mantle = "#181825"
base = "#1e1e2e"
red = "#f38ba8"
lavender = "#b4befe"
blue = "#89b4fa"
green = "#a6e3a1"
maroon = "#eba0ac"
mauve = "#cba6f7"
peach = "#fab387"
text = "#cdd6f4"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"

[directory]
style = "blue"
format = "[$path]($style)[$read_only]($read_only_style) "

[character]
success_symbol = "[❯](red)"
error_symbol = "[❯](base)"
vimcmd_symbol = "[❮](green)"

[git_branch]
style = "text"
format = "[$branch(:$remote_branch)]($style) "

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](red)($ahead_behind$stashed)]($style)"
ahead = "> "
behind = "< "
conflicted = ">< "
untracked = "? "
modified = "! "
staged = "+ "
renamed = ">> "
deleted = "X "
stashed = "≡ "

[python]
format = "[$virtualenv](surface2)"




